### ISSUE TITLE
Use oclif

### ISSUE THREAD

**Issue by nemuvski** [nemuvski/chaka#1]
💪 https://oclif.io/

## To-Do

- [x] Update `README.md`
  - write new specification
- Use oclif
  - [x] Implement `react` command
  - [x] Implement `next` command
- [x] Create `DEV.md`

**Comment by nemuvski** [comment]
## New specification

```
USAGE
  $ chaka [COMMAND]

COMMANDS
  help   Display help for chaka.
  next   Create a Next.js project template
  react  Create a React.js project template
```

### `react` command

```
USAGE
  $ chaka react [PROJECT] [-t vite|webpack]

ARGUMENTS
  PROJECT  project name (i.e. directory name)

FLAGS
  -t, --tool=<option>  [default: vite] build tool name
                       <options: vite|webpack>
```

### `next` command

```
USAGE
  $ chaka next [PROJECT]

ARGUMENTS
  PROJECT  project name (i.e. directory name)
```
